// Date: 12/16/2013 8:21:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package powercrystals.minefactoryreloaded.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Skybot extends ModelBase
{
	//fields
	ModelRenderer Base;
	ModelRenderer Shaft;
	ModelRenderer Fin1;
	ModelRenderer Fin2;
	ModelRenderer Fin3;

	public Skybot()
	{
		textureWidth = 64;
		textureHeight = 64;

		Base = new ModelRenderer(this, 0, 0);
		Base.addBox(-4F, 0F, -4F, 8, 8, 8);
		Base.setRotationPoint(0F, 0F, 0F);
		Base.setTextureSize(64, 64);
		Base.mirror = true;
		setRotation(Base, 0F, 0F, 0F);
		Shaft = new ModelRenderer(this, 0, 0);
		Shaft.addBox(-1F, 0F, -1F, 2, 2, 2);
		Shaft.setRotationPoint(0F, -2F, 0F);
		Shaft.setTextureSize(64, 64);
		Shaft.mirror = true;
		setRotation(Shaft, 0F, 0F, 0F);
		Fin1 = new ModelRenderer(this, 0, 16);
		Fin1.addBox(0F, 0F, -2F, 16, 2, 4);
		Fin1.setRotationPoint(0F, -4F, 0F);
		Fin1.setTextureSize(64, 64);
		Fin1.mirror = true;
		setRotation(Fin1, 0F, 0F, 0F);
		Fin2 = new ModelRenderer(this, 0, 22);
		Fin2.addBox(0F, 0F, -2F, 16, 2, 4);
		Fin2.setRotationPoint(0F, -4F, 0F);
		Fin2.setTextureSize(64, 64);
		Fin2.mirror = true;
		setRotation(Fin2, 0F, 2.094395F, 0F);
		Fin3 = new ModelRenderer(this, 0, 16);
		Fin3.addBox(0F, 0F, -2F, 16, 2, 4);
		Fin3.setRotationPoint(0F, -4F, 0F);
		Fin3.setTextureSize(64, 64);
		Fin3.mirror = true;
		setRotation(Fin3, 0F, -2.094395F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Base.render(f5);
		Shaft.render(f5);
		Fin1.render(f5);
		Fin2.render(f5);
		Fin3.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
