package powercrystals.minefactoryreloaded.asm.plugin;

import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.relauncher.IFMLLoadingPlugin;

import java.util.Map;

@IFMLLoadingPlugin.TransformerExclusions({ "powercrystals.minefactoryreloaded.asm.plugin" })
@IFMLLoadingPlugin.SortingIndex(1002)
@IFMLLoadingPlugin.Name("MFR Loading Plugin")
public class LoadingPlugin implements IFMLLoadingPlugin {

	@Override
	public String[] getASMTransformerClass() {

		return new String[] { "powercrystals.minefactoryreloaded.asm.plugin.MFRClassTransformer" };
	}

	@Override
	public String getModContainerClass() {

		return MFRDummyContainer.class.getName();
	}

	@Override
	public String getSetupClass() {

		return null;
	}

	@Override
	public void injectData(Map<String, Object> data) {

	}

	@Override
	public String getAccessTransformerClass() {

		return null;
	}

	public static class MFRDummyContainer extends DummyModContainer {

		public MFRDummyContainer() {

			super(new ModMetadata());
			ModMetadata md = getMetadata();
			md.autogenerated = true;
			md.modId = "<MFR ASM>";
			md.name = md.description = "MFR ASM";
			md.parent = "minefactoryreloaded";
			md.version = "000";
		}
	}
}
